version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: challenge4-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    image: solution-01 # Reference the image you created in Challenge 3
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3000:3000"
    deploy:
      replicas: 3 # Scale the Node.js service to 3 instances
    depends_on:
      - db

  nginx:
    image: nginx:latest # Use the nginx image from Challenge 3
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  db_data:
